# Python script
# Run a Python file or inline script
- task: PythonScript@0
  inputs: 
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    #scriptSource: 'filePath' # Options: filePath, inline
    #scriptPath: # Required when scriptSource == filePath
    #script: # Required when scriptSource == inline
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
    